name: publish
on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    # Standard usage
    - uses:  helaili/jekyll-action@2.0.0
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
        LC_ALL: "C.UTF-8"
        LANG: "ja_JP.UTF-8"
        LANGUAGE: "ja_JP.UTF-8"